Dodanie wsparcia dla setTrackingNumber w kliencie PublicApi
LinkerCloud/linker-api-client pull request #4
Opened 2018-05-24 14:43 UTC by jasufo

2018-05-24 14:44 UTC, hrba commented on src/Linker/Api/Client/HttpApiClient.php
> +use http\Env\Request;
Wrong import

2018-05-24 14:45 UTC, hrba commented on src/Linker/Api/Client/HttpApiClient.php
>  }
No new line at end of file

2018-05-24 14:45 UTC, hrba requested changes

2018-05-24 14:45 UTC, hrba commented on src/Linker/Api/LinkerClientInterface.php
> +use http\Env\Request;
Wrong import

2018-05-25 08:29 UTC, michalploneczka commented on src/Linker/Api/Client/HttpApiClient.php
> +        echo $content;
echo.... :)

2018-05-25 20:44 UTC, hrba approved these changes

2018-05-25 20:45 UTC, merged